source 'https://rubygems.org'


gem 'sinatra'
gem 'sinatra-flash'

group :development, :test do
  gem 'cucumber'
  gem 'cucumber-sinatra'
  gem 'capybara'

  gem 'rspec'
  gem 'rspec-autotest'

  gem 'rack-test'
  gem 'rack_session_access'

  gem 'byebug', '11.0.0'
  gem 'launchy'
  gem 'rerun'
  gem 'guard'
  gem 'simplecov'
  gem 'webmock'
  gem 'ZenTest'
end
